name: Deploy Databricks Bundle

on:
  push:
    branches:
      - main
    paths:
      - asset_bundles/**

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Databricks CLI
        run: curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh

      - name: Deploy bundle
        working-directory: asset_bundles
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          DATABRICKS_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        run: databricks bundle deploy -t ci
